// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "about" section.

import React from 'react';
import AboutTestimonial from "@/components/sections/about/AboutTestimonial";

export default function AboutSection(): React.JSX.Element {
  return (
    <div id="about" data-section="about">
              <AboutTestimonial
                textAnimation="slide-up"
                tag="About YCA Landscaping LLC"
                quote="We’ve spent years creating outdoor spaces that homeowners love coming home to. From the first design to the final detail, we’re committed to quality landscapes that last."
                author=""
                role=""
                videoSrc="https://storage.googleapis.com/webild/default/templates/landscaping/about-video.mp4"
              />
            </div>
  );
}
