// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "contact" section.

import React from 'react';
import ContactSplitForm from "@/components/sections/contact/ContactSplitForm";

export default function ContactSection(): React.JSX.Element {
  return (
    <div id="contact" data-section="contact">
              <ContactSplitForm
                textAnimation="slide-up"
                tag="Contact"
                title="Get Your Free Estimate Today Today"
                description="Tell us about your project and we'll get back to you within 24 hours."
                inputs={[
                  { name: "name", type: "text", placeholder: "Full Name", required: true },
                  { name: "email", type: "email", placeholder: "Email Address", required: true },
                  { name: "phone", type: "tel", placeholder: "Phone Number" },
                ]}
                textarea={{ name: "message", placeholder: "Tell us about your project...", rows: 4, required: true }}
                buttonText="Send Message"
                imageSrc="https://storage.googleapis.com/webild/default/templates/landscaping/img-2.jpg?_wi=1"
              />
            </div>
  );
}
