// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "faq" section.

import React from 'react';
import FaqTwoColumn from "@/components/sections/faq/FaqTwoColumn";

export default function FaqSection(): React.JSX.Element {
  return (
    <div id="faq" data-section="faq">
              <FaqTwoColumn
                textAnimation="slide-up"
                tag=""
                title="Frequently Asked Questions"
                description="Everything you need to know about our landscaping services."
                items={[
                  {
                    question: "How long does a typical landscaping project take?",
                    answer: "Most residential projects take 1-3 weeks depending on scope. We'll provide a detailed timeline during your consultation so you know exactly what to expect.",
                  },
                  {
                    question: "Do you offer free consultations?",
                    answer: "Yes! We offer complimentary on-site consultations where we assess your property, discuss your vision, and provide a detailed estimate — no obligation.",
                  },
                  {
                    question: "What areas do you serve?",
                    answer: "We serve the greater metropolitan area and surrounding suburbs within a 50-mile radius. Contact us to confirm service availability in your location.",
                  },
                  {
                    question: "Do you provide ongoing maintenance?",
                    answer: "Absolutely. We offer weekly, bi-weekly, and monthly maintenance plans that include mowing, trimming, fertilization, and seasonal cleanups.",
                  },
                  {
                    question: "Are your practices eco-friendly?",
                    answer: "Yes, sustainability is core to our approach. We use native plants, organic fertilizers, smart irrigation, and environmentally responsible methods whenever possible.",
                  },
                  {
                    question: "Do you handle permits and HOA approvals?",
                    answer: "We handle all necessary permits and can work directly with your HOA to ensure your project meets community guidelines and gets approved smoothly.",
                  },
                ]}
              />
            </div>
  );
}
