// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "hero" section.

import React from 'react';
import HeroOverlayTestimonial from "@/components/sections/hero/HeroOverlayTestimonial";

export default function HeroSection(): React.JSX.Element {
  return (
    <div id="hero" data-section="hero">
              <HeroOverlayTestimonial
                textAnimation="slide-up"
                tag="Professional Landscaping"
                title="Transform Your Outdoor Space Today Today"
                description="Transform your outdoor space with landscaping designed around your vision. From elegant gardens to custom hardscapes, we create and maintain landscapes that make your property stand out.

    "
                primaryButton={{ text: "Get Free Estimate", href: "#contact" }}
                secondaryButton={{ text: "Our Services", href: "#services" }}
                imageSrc="https://storage.googleapis.com/webild/default/templates/landscaping/hero.jpg"
                testimonials={[
                  {
                    name: "Sarah M.",
                    handle: "Homeowner",
                    text: "YCA Landscaping LLC completely transformed our backyard. The team was professional, creative, and delivered beyond our expectations.",
                    rating: 5,
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-2.jpg",
                  },
                  {
                    name: "David K.",
                    handle: "Property Manager",
                    text: "We've used YCA Landscaping LLC for all our commercial properties. Their maintenance plans keep everything looking pristine year-round.",
                    rating: 5,
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/web-agency-2/team-1.jpg",
                  },
                ]}
              />
            </div>
  );
}
