// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesDetailedSteps from "@/components/sections/features/FeaturesDetailedSteps";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesDetailedSteps
                textAnimation="slide-up"
                tag="Our Services"
                title="What Services We Offer"
                description="From design to maintenance, we handle every aspect of your landscape."
                steps={[
                  {
                    tag: "Design",
                    title: "Lawn Care ",
                    subtitle: "Custom Plans",
                    description: "IIs your lawn looking rough, thin, or neglected? Let us bring the green back and give your yard the fresh, healthy look it deserves.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-2.jpg",
                  },
                  {
                    tag: "Installation",
                    title: "Property Cleanup",
                    subtitle: "Cleanups",
                    description: "From messy and overgrown to clean and under control. We transform neglected properties into clean, presentable spaces that stand out.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-3.jpg",
                  },
                  {
                    tag: "Maintenance",
                    title: "Tree Trimming",
                    subtitle: "Tree Service",
                    description: "Overgrown trees can quickly take away from your property’s curb appeal. Let us trim, shape, and clean them up so your property can stand out again.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-4.jpg",
                  },
                  {
                    tag: "Irrigation",
                    title: "Sod Installations",
                    subtitle: "Grass Management",
                    description: "Fresh sod, fresh look, fresh start. We turn empty or struggling spaces into beautiful green lawns that make your property stand out.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-5.jpg",
                  },
                ]}
              />
            </div>
  );
}
