/* eslint-disable */
// @ts-nocheck — generated by catalog-eject; runtime-correct but TS strict-mode false-positives on inlined catalog body
import Button from "@/components/ui/Button";
import TextAnimation from "@/components/ui/TextAnimation";
import ImageOrVideo from "@/components/ui/ImageOrVideo";
import ScrollReveal from "@/components/ui/ScrollReveal";
import { cls } from "@/lib/utils";

const steps = [
  {
    tag: "",
    title: "Lawn Care ",
    subtitle: "Lawn  ",
    description: "IIs your lawn looking rough, thin, or neglected? Let us bring the green back and give your yard the fresh, healthy look it deserves.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789232566300-uz7ds8sk.jpg"
  },
  {
    tag: "",
    title: "Property Cleanup",
    subtitle: "Cleanups",
    description: "From messy and overgrown to clean and under control. We transform neglected properties into clean, presentable spaces that stand out.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231698871-a3tjsnz8.png"
  },
  {
    tag: "",
    title: "Tree Trimming",
    subtitle: "Tree Service",
    description: "Overgrown trees can quickly take away from your property’s curb appeal. Let us trim, shape, and clean them up so your property can stand out again.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789323954133-irq2w8h7.jpg"
  },
  {
    tag: "",
    title: "Sod Insallation",
    subtitle: "Grass Management",
    description: "Fresh sod, fresh look, fresh start. We turn empty or struggling spaces into beautiful green lawns that make your property stand out.",
    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231748024-oyah0nhq.jpg"
  }
];

type StepItem = {
  tag: string;
  title: string;
  subtitle: string;
  description: string;
} & ({ imageSrc: string; videoSrc?: never } | { videoSrc: string; imageSrc?: never });

interface FeaturesDetailedStepsProps {
  tag: string;
  title: string;
  description: string;
  primaryButton?: { text: string; href: string };
  secondaryButton?: { text: string; href: string };
  steps: StepItem[];
  textAnimation: "slide-up" | "fade-blur" | "fade";
}

const ServicesInline = () => {
  return (
    <section aria-label="Features detailed steps section" className="py-20">
      <div className="flex flex-col gap-8 md:gap-10">
        <div className="flex flex-col items-center w-content-width mx-auto gap-2">
          <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
            <p>{"Our Services"}</p>
          </div>

          <TextAnimation
            text={"What Services We Offer"}
            variant={"slide-up"}
            gradientText={true}
            tag="h2"
            className="md:max-w-8/10 text-6xl 2xl:text-7xl leading-[1.15] font-semibold text-center text-balance"
          />

          <TextAnimation
            text={"From design to maintenance, we handle every aspect of your landscape."}
            variant={"slide-up"}
            gradientText={false}
            tag="p"
            className="md:max-w-7/10 text-lg md:text-xl leading-snug text-center text-balance"
          />

          {(undefined || undefined) && (
            <div className="flex flex-wrap justify-center gap-3 mt-2 md:mt-3">
              {undefined && <Button text={undefined.text} href={undefined.href} variant="primary"/>}
              {undefined && <Button text={undefined.text} href={undefined.href} variant="secondary"animationDelay={0.1} />}
            </div>
          )}
        </div>

        <div className="flex flex-col w-content-width mx-auto gap-5">
          {steps.map((step, index) => {
            const stepNumber = String(index + 1).padStart(2, "0");
            return (
              <ScrollReveal
                variant="slide-up"
                key={step.title}
                className="flex flex-col md:flex-row justify-between 2xl:w-8/10 mx-auto gap-6 p-6 md:p-10 card rounded overflow-hidden"
              >
                <div className="flex flex-col justify-between w-full md:w-1/2">
                  <div className="flex flex-col gap-2">
                    <div className="px-3 py-1 mb-1 text-sm card rounded w-fit">
                      <p>{step.tag}</p>
                    </div>
                    <h3 className="text-7xl md:text-8xl font-semibold leading-[1.15] text-balance">{step.title}</h3>
                  </div>
                  <div className="block md:hidden w-full h-px my-5 bg-accent/20" />
                  <div className="flex flex-col gap-2">
                    <h4 className="text-2xl md:text-3xl font-semibold leading-snug text-balance">{step.subtitle}</h4>
                    <p className="text-base md:text-lg leading-snug text-balance">{step.description}</p>
                  </div>
                </div>
                <div className="flex flex-col w-full md:w-35/100 gap-10">
                  <span className="hidden md:block self-end text-7xl md:text-8xl font-semibold text-accent">{stepNumber}</span>
                  <div className="aspect-square rounded overflow-hidden">
                    <ImageOrVideo imageSrc={step.imageSrc} videoSrc={step.videoSrc} />
                  </div>
                </div>
              </ScrollReveal>
            );
          })}
        </div>
      </div>
    </section>
  );
};

export default function ServicesSection() {
  return (
    <div data-webild-section="services" data-section="services" id="services">
      <ServicesInline />
    </div>
  );
}
