// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "services" section.

import React from 'react';
import FeaturesDetailedSteps from "@/components/sections/features/FeaturesDetailedSteps";

export default function ServicesSection(): React.JSX.Element {
  return (
    <div id="services" data-section="services">
              <FeaturesDetailedSteps
                textAnimation="slide-up"
                tag="Our Services"
                title="What Services We Offer"
                description="From design to maintenance, we handle every aspect of your landscape."
                steps={[
                  {
                    tag: "",
                    title: "Lawn Care ",
                    subtitle: "Lawn  ",
                    description: "IIs your lawn looking rough, thin, or neglected? Let us bring the green back and give your yard the fresh, healthy look it deserves.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789232566300-uz7ds8sk.jpg",
                  },
                  {
                    tag: "",
                    title: "Property Cleanup",
                    subtitle: "Cleanups",
                    description: "From messy and overgrown to clean and under control. We transform neglected properties into clean, presentable spaces that stand out.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231698871-a3tjsnz8.png",
                  },
                  {
                    tag: "",
                    title: "Tree Trimming",
                    subtitle: "Tree Service",
                    description: "Overgrown trees can quickly take away from your property’s curb appeal. Let us trim, shape, and clean them up so your property can stand out again.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789323954133-irq2w8h7.jpg",
                  },
                  {
                    tag: "",
                    title: "Sod Insallation",
                    subtitle: "Grass Management",
                    description: "Fresh sod, fresh look, fresh start. We turn empty or struggling spaces into beautiful green lawns that make your property stand out.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231748024-oyah0nhq.jpg",
                  },
                ]}
              />
            </div>
  );
}
