// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "team" section.

import React from 'react';
import TeamOverlayCards from "@/components/sections/team/TeamOverlayCards";

export default function TeamSection(): React.JSX.Element {
  return (
    <div id="team" data-section="team">
              <TeamOverlayCards
                textAnimation="slide-up"
                tag="Our Team"
                title="Meet the Experts"
                description="The skilled professionals behind every beautiful landscape."
                members={[
                  {
                    name: "James Carter",
                    role: "Lead Designer",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-11.jpg",
                  },
                  {
                    name: "Maria Silva",
                    role: "Horticulturist",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-10.jpg",
                  },
                  {
                    name: "Ryan Mitchell",
                    role: "Project Manager",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-9.jpg",
                  },
                ]}
              />
            </div>
  );
}
