// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-us" section.

import React from 'react';
import TeamGlassCards from "@/components/sections/team/TeamGlassCards";

export default function WhyUsSection(): React.JSX.Element {
  return (
    <div id="why-us" data-section="why-us">
              <TeamGlassCards
                textAnimation="slide-up"
                tag=""
                title="Why Choose YCA Landscaping LLC"
                description="What sets us apart from the rest."
                members={[
                  {
                    name: "Expert Craftsmanship",
                    role: "Decades of combined experience in landscape design and installation.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-6.jpg",
                  },
                  {
                    name: "Eco-Friendly Approach",
                    role: "Sustainable practices and native plant selections that thrive naturally.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-7.jpg",
                  },
                  {
                    name: "Full-Service Care",
                    role: "From initial design to ongoing maintenance, we handle everything.",
                    imageSrc: "https://storage.googleapis.com/webild/default/templates/landscaping/img-8.jpg",
                  },
                ]}
              />
            </div>
  );
}
