// AUTO-GENERATED by per-section-migrate. Edit freely — Bob will treat this
// file as the canonical source for the "why-us" section.

import React from 'react';
import TeamGlassCards from "@/components/sections/team/TeamGlassCards";

export default function WhyUsSection(): React.JSX.Element {
  return (
    <div id="why-us" data-section="why-us">
              <TeamGlassCards
                textAnimation="slide-up"
                tag=""
                title="Why Choose YCA Landscaping LLC"
                description="What sets us apart from the rest."
                members={[
                  {
                    name: "Expert Craftsmanship",
                    role: "We take pride in our craft, delivering professional landscaping with a level of detail you can see in every corner.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789232721713-s9k9fj9w.jpg",
                  },
                  {
                    name: "Eco-Friendly Approach",
                    role: "We go beyond basic landscaping to deliver results that make your property stand out.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231948484-rzducj4e.jpg",
                  },
                  {
                    name: "Full-Service Care",
                    role: "From initial design to ongoing maintenance, we handle everything.",
                    imageSrc: "https://storage.googleapis.com/webild/users/user_3JCBXteeismv9BMFxhwlNrCxP4l/uploaded-1789231847821-okuvrzjv.jpg",
                  },
                ]}
              />
            </div>
  );
}
